name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Ejecuta el flujo de trabajo en cada push a la rama 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.*'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Asegúrate de que Sphinx y autodoc estén en requirements.txt
        pip install sphinx-rtd-theme  # Instala el tema si lo usas

    - name: Build Sphinx documentation
      run: |
        cd docs  # Cambia esto si tu carpeta de documentación tiene otro nombre
        make html  # Compila la documentación en HTML

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html  # Ruta donde se generaron los HTML de Sphinx
        publish_branch: gh-pages
        keep_files: true  # Mantiene los archivos anteriores en gh-pages (opcional)
