name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy documentation
        run: |
          mkdir -p docs/source/_build/html  # Crea el directorio de destino si no existe
          cp -r docs/build/html/* docs/source/_build/html/  # Copia el contenido de build/html a la carpeta de destino

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/source/_build/html
