name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx

      - name: Set PYTHONPATH and build documentation
        working-directory: docs/source
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/src"  # Asegura que 'src' esté en el PYTHONPATH
          sphinx-build -b html -E . _build/html         # Fuerza la reconstrucción de la doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/source/_build/html
